version: "3.9"
name: block-list
services:
  db:
    container_name: block-list-db
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=block-list
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: